"""AI Learning Planner + AI Skill Diagnosis (spec sections 37-39). The 7-day
plan ITSELF is already generated deterministically by
`app/interview_engine/plan.py` from real mastery/weakness data — this
template only explains why each already-chosen day was chosen (section 38:
"Do not let AI arbitrarily rewrite the curriculum"). Skill diagnosis is an
AI-only observation, explicitly not written back into UserSkill.mastery_score
(see AISkillDiagnosis model docstring)."""

from app.ai.prompts.base import PromptTemplate
from app.models.enums import AIFeature, AIMode
from app.schemas.ai import AIPlanExplanationResult, AISkillDiagnosisResult

LEARNING_PLANNER = PromptTemplate(
    feature=AIFeature.LEARNING_PLANNER,
    version="1.0",
    purpose="Explain why each day of the real, already-generated 7-day InterviewPlan was selected, "
    "using the real mastery/weakness/readiness data behind it.",
    input_schema={
        "plan_days": "the real PlanDaySchema list (day_number, focus_area, title, task_type, description)",
        "weaknesses": "real WeaknessFindingSchema list behind the plan",
        "readiness": "real ReadinessResponse behind the plan",
    },
    output_schema=AIPlanExplanationResult,
    default_mode=AIMode.EXPLAINER,
    instructions="""You are given the REAL 7-day plan already generated by the platform's own \
deterministic planner, plus the real weakness/readiness data it was built from. For each day \
(matching `day_number` exactly — never add, remove, or reorder days), write one sentence \
explaining why THAT day's focus area/task was chosen, referencing the specific weakness/readiness \
data given (e.g. "Day 2 targets A/B testing because it's your weakest readiness area at 42%, with 3 \
recent Experimentation questions scored below 60"). Never invent a different day or task than what \
was given.""",
)

SKILL_DIAGNOSIS = PromptTemplate(
    feature=AIFeature.SKILL_DIAGNOSIS,
    version="1.0",
    purpose="AI Skill Diagnosis after an exercise (spec section 39) — a soft, AI-only observation "
    "stored separately from the real mastery score.",
    input_schema={
        "exercise": "prompt/skill/difficulty",
        "attempt": "real ExerciseAttempt (score, submitted_answer, hints_used)",
        "mastery": "real current UserSkill.mastery_score for the exercise's skill",
    },
    output_schema=AISkillDiagnosisResult,
    default_mode=AIMode.ANALYST,
    instructions="""Diagnose this one exercise attempt. You're given the real exercise, the \
learner's real submitted answer/score, and their real current mastery score for this skill (do not \
restate or alter that mastery number — you are not computing mastery). Identify specific strength \
and improvement areas grounded in what was actually submitted (e.g. "correctly used a window \
function" or "the join produced duplicate rows before aggregation" only if the submission actually \
shows that), and recommend 1-3 specific kinds of follow-up practice.""",
)
