"""phase 11 career readiness and job preparation

Revision ID: 4d9c395b6197
Revises: b09cef974055
Create Date: 2026-09-09 09:48:24.549226

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9c395b6197'
down_revision: str | None = 'b09cef974055'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_slug'), 'achievements', ['slug'], unique=True)
    op.create_table('role_templates',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('DATA_ANALYST', 'PRODUCT_ANALYST', 'BUSINESS_ANALYST', 'BI_ANALYST', 'MARKETING_ANALYST', 'ANALYTICS_ENGINEER_ENTRY', 'ANALYTICS_ENGINEER_INTERMEDIATE', name='targetrolecategory', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('core_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('nice_to_have_skills', sa.JSON(), nullable=False),
    sa.Column('typical_responsibilities', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_reference', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_slug'), 'role_templates', ['slug'], unique=True)
    op.create_table('behavioral_stories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('AMBIGUITY', 'COMMUNICATION', 'CONFLICT', 'DEADLINES', 'DISAGREEMENT', 'WORKING_WITH_ENGINEERS', 'FAILURE', 'INCOMPLETE_DATA', 'INFLUENCING', 'OWNERSHIP', 'PRIORITIZATION', 'STAKEHOLDER_MANAGEMENT', name='behavioralstorycategory', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('related_question_ids', sa.JSON(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_stories_user_id'), 'behavioral_stories', ['user_id'], unique=False)
    op.create_table('career_goals',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal_type', sa.Enum('TARGET_ROLE', 'SKILL_MASTERY', 'READINESS_LEVEL', 'PORTFOLIO_COMPLETION', 'INTERVIEW_PREP', 'CUSTOM', name='careergoaltype', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.String(length=200), nullable=True),
    sa.Column('current_value', sa.String(length=200), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='careergoalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goals_user_id'), 'career_goals', ['user_id'], unique=False)
    op.create_table('career_notes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_notes_user_id'), 'career_notes', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('is_public_ready', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_portfolios_user_id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('target_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_template_id', sa.String(length=36), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_roles_role_template_id'), 'target_roles', ['role_template_id'], unique=False)
    op.create_index(op.f('ix_target_roles_user_id'), 'target_roles', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=36), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('career_assessments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_role_id', sa.String(length=36), nullable=True),
    sa.Column('rubric_scores', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_readiness_level', sa.Enum('FOUNDATION', 'DEVELOPING', 'INTERMEDIATE', 'INTERVIEW_READY', 'STRONG_CANDIDATE', 'EXCEPTIONAL', name='careerreadinesslevel', native_enum=False, length=30), nullable=False),
    sa.Column('gating_passed', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessments_target_role_id'), 'career_assessments', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_career_assessments_user_id'), 'career_assessments', ['user_id'], unique=False)
    op.create_table('career_milestones',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_type', sa.Enum('SKILL_LEVEL_UP', 'PROJECT_COMPLETED', 'CASE_COMPLETED', 'INTERVIEW_COMPLETED', 'ASSESSMENT_PASSED', 'GOAL_COMPLETED', 'READINESS_LEVEL_UP', 'ACHIEVEMENT_EARNED', name='careermilestonetype', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('related_goal_id', sa.String(length=36), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['related_goal_id'], ['career_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_milestones_user_id'), 'career_milestones', ['user_id'], unique=False)
    op.create_table('career_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('primary_target_role_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['primary_target_role_id'], ['target_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_career_profiles_user_id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_role_id', sa.String(length=36), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('PASTED', 'UPLOADED', name='jdsource', native_enum=False, length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_target_role_id'), 'job_descriptions', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('PROJECT', 'CASE_STUDY', 'CERTIFICATION', 'ACHIEVEMENT', 'SKILL_HIGHLIGHT', name='portfolioitemtype', native_enum=False, length=30), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('privacy', sa.Enum('PRIVATE', 'PORTFOLIO', 'PUBLIC_READY', name='privacylevel', native_enum=False, length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_portfolio_id'), 'portfolio_items', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_ref_id'), 'portfolio_items', ['ref_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('PASTED', 'UPLOADED', name='resumesource', native_enum=False, length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('jd_analyses',
    sa.Column('job_description_id', sa.String(length=36), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_analyses_job_description_id'), 'jd_analyses', ['job_description_id'], unique=False)
    op.create_table('jd_requirements',
    sa.Column('job_description_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('SKILL', 'TOOL', 'RESPONSIBILITY', 'EXPERIENCE', 'EDUCATION', 'DOMAIN_KNOWLEDGE', 'SOFT_SKILL', 'BUSINESS_EXPECTATION', name='jdrequirementkind', native_enum=False, length=30), nullable=False),
    sa.Column('priority', sa.Enum('MUST_HAVE', 'STRONGLY_PREFERRED', 'NICE_TO_HAVE', name='jdrequirementpriority', native_enum=False, length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('matched_skill_slug', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_requirements_job_description_id'), 'jd_requirements', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_jd_requirements_matched_skill_slug'), 'jd_requirements', ['matched_skill_slug'], unique=False)
    op.create_table('job_preparation_workspaces',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_description_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'IN_PROGRESS', 'READY', 'ARCHIVED', name='jobprepstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_description_id', name='uq_job_prep_workspace_jd_id')
    )
    op.create_index(op.f('ix_job_preparation_workspaces_job_description_id'), 'job_preparation_workspaces', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_job_preparation_workspaces_user_id'), 'job_preparation_workspaces', ['user_id'], unique=False)
    op.create_table('resume_evidence',
    sa.Column('resume_version_id', sa.String(length=36), nullable=False),
    sa.Column('skill_slug', sa.String(length=150), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_evidence_project_id'), 'resume_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_resume_evidence_resume_version_id'), 'resume_evidence', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_resume_evidence_skill_slug'), 'resume_evidence', ['skill_slug'], unique=False)
    op.create_table('resume_reviews',
    sa.Column('resume_version_id', sa.String(length=36), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_reviews_resume_version_id'), 'resume_reviews', ['resume_version_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_description_id', sa.String(length=36), nullable=True),
    sa.Column('target_role_id', sa.String(length=36), nullable=True),
    sa.Column('skill_slug', sa.String(length=150), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('MUST_HAVE', 'STRONGLY_PREFERRED', 'NICE_TO_HAVE', name='jdrequirementpriority', native_enum=False, length=30), nullable=True),
    sa.Column('current_mastery_score', sa.Float(), nullable=False),
    sa.Column('gap_size', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_job_description_id'), 'skill_gaps', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_skill_slug'), 'skill_gaps', ['skill_slug'], unique=False)
    op.create_index(op.f('ix_skill_gaps_target_role_id'), 'skill_gaps', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_user_id'), 'skill_gaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gaps_user_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_target_role_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_skill_slug'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_job_description_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_resume_reviews_resume_version_id'), table_name='resume_reviews')
    op.drop_table('resume_reviews')
    op.drop_index(op.f('ix_resume_evidence_skill_slug'), table_name='resume_evidence')
    op.drop_index(op.f('ix_resume_evidence_resume_version_id'), table_name='resume_evidence')
    op.drop_index(op.f('ix_resume_evidence_project_id'), table_name='resume_evidence')
    op.drop_table('resume_evidence')
    op.drop_index(op.f('ix_job_preparation_workspaces_user_id'), table_name='job_preparation_workspaces')
    op.drop_index(op.f('ix_job_preparation_workspaces_job_description_id'), table_name='job_preparation_workspaces')
    op.drop_table('job_preparation_workspaces')
    op.drop_index(op.f('ix_jd_requirements_matched_skill_slug'), table_name='jd_requirements')
    op.drop_index(op.f('ix_jd_requirements_job_description_id'), table_name='jd_requirements')
    op.drop_table('jd_requirements')
    op.drop_index(op.f('ix_jd_analyses_job_description_id'), table_name='jd_analyses')
    op.drop_table('jd_analyses')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_portfolio_items_ref_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_portfolio_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_target_role_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    op.drop_index(op.f('ix_career_milestones_user_id'), table_name='career_milestones')
    op.drop_table('career_milestones')
    op.drop_index(op.f('ix_career_assessments_user_id'), table_name='career_assessments')
    op.drop_index(op.f('ix_career_assessments_target_role_id'), table_name='career_assessments')
    op.drop_table('career_assessments')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_target_roles_user_id'), table_name='target_roles')
    op.drop_index(op.f('ix_target_roles_role_template_id'), table_name='target_roles')
    op.drop_table('target_roles')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_career_notes_user_id'), table_name='career_notes')
    op.drop_table('career_notes')
    op.drop_index(op.f('ix_career_goals_user_id'), table_name='career_goals')
    op.drop_table('career_goals')
    op.drop_index(op.f('ix_behavioral_stories_user_id'), table_name='behavioral_stories')
    op.drop_table('behavioral_stories')
    op.drop_index(op.f('ix_role_templates_slug'), table_name='role_templates')
    op.drop_table('role_templates')
    op.drop_index(op.f('ix_achievements_slug'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
