"""python lab

Revision ID: 988f6ea7cd4f
Revises: 2f23ec3c5afc
Create Date: 2026-09-02 05:51:58.890562

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988f6ea7cd4f'
down_revision: str | None = '2f23ec3c5afc'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('python_workspaces',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('selected_dataset', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_workspaces_user_id'), 'python_workspaces', ['user_id'], unique=False)
    op.create_table('python_cells',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['python_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_cells_workspace_id'), 'python_cells', ['workspace_id'], unique=False)
    op.create_table('python_executions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['python_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_executions_user_id'), 'python_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_python_executions_workspace_id'), 'python_executions', ['workspace_id'], unique=False)
    op.create_table('python_runtimes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('container_id', sa.String(length=200), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['python_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_runtimes_user_id'), 'python_runtimes', ['user_id'], unique=False)
    op.create_index(op.f('ix_python_runtimes_workspace_id'), 'python_runtimes', ['workspace_id'], unique=False)
    op.create_table('python_exercise_test_results',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exercise_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_python_exercise_test_results_attempt_id'), 'python_exercise_test_results', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_python_exercise_test_results_attempt_id'), table_name='python_exercise_test_results')
    op.drop_table('python_exercise_test_results')
    op.drop_index(op.f('ix_python_runtimes_workspace_id'), table_name='python_runtimes')
    op.drop_index(op.f('ix_python_runtimes_user_id'), table_name='python_runtimes')
    op.drop_table('python_runtimes')
    op.drop_index(op.f('ix_python_executions_workspace_id'), table_name='python_executions')
    op.drop_index(op.f('ix_python_executions_user_id'), table_name='python_executions')
    op.drop_table('python_executions')
    op.drop_index(op.f('ix_python_cells_workspace_id'), table_name='python_cells')
    op.drop_table('python_cells')
    op.drop_index(op.f('ix_python_workspaces_user_id'), table_name='python_workspaces')
    op.drop_table('python_workspaces')
    # ### end Alembic commands ###
