"""sql lab

Revision ID: 2f23ec3c5afc
Revises: ffb90bbf171e
Create Date: 2026-09-01 23:36:44.952283

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f23ec3c5afc'
down_revision: str | None = 'ffb90bbf171e'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_query_history',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_query_history_user_id'), 'sql_query_history', ['user_id'], unique=False)
    op.create_table('sql_tables',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('grain', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_tables_dataset_id'), 'sql_tables', ['dataset_id'], unique=False)
    op.create_table('sql_workspaces',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_workspaces_user_id'), 'sql_workspaces', ['user_id'], unique=False)
    op.create_table('sql_saved_queries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['sql_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_saved_queries_user_id'), 'sql_saved_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_sql_saved_queries_workspace_id'), 'sql_saved_queries', ['workspace_id'], unique=False)
    op.create_table('sql_exercise_test_results',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exercise_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_exercise_test_results_attempt_id'), 'sql_exercise_test_results', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sql_exercise_test_results_attempt_id'), table_name='sql_exercise_test_results')
    op.drop_table('sql_exercise_test_results')
    op.drop_index(op.f('ix_sql_saved_queries_workspace_id'), table_name='sql_saved_queries')
    op.drop_index(op.f('ix_sql_saved_queries_user_id'), table_name='sql_saved_queries')
    op.drop_table('sql_saved_queries')
    op.drop_index(op.f('ix_sql_workspaces_user_id'), table_name='sql_workspaces')
    op.drop_table('sql_workspaces')
    op.drop_index(op.f('ix_sql_tables_dataset_id'), table_name='sql_tables')
    op.drop_table('sql_tables')
    op.drop_index(op.f('ix_sql_query_history_user_id'), table_name='sql_query_history')
    op.drop_table('sql_query_history')
    # ### end Alembic commands ###
