"""phase 2 content engine

Revision ID: ffb90bbf171e
Revises: 173fd191a6a1
Create Date: 2026-09-01 12:23:14.885075

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb90bbf171e'
down_revision: str | None = '173fd191a6a1'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('assessments',
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('retry_policy', sa.Enum('UNLIMITED', 'LIMITED', name='assessmentretrypolicy', native_enum=False, length=20), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_module_id'), 'assessments', ['module_id'], unique=False)
    op.create_index(op.f('ix_assessments_slug'), 'assessments', ['slug'], unique=True)
    op.create_table('module_prerequisites',
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_module_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id', 'prerequisite_module_id')
    )
    op.create_table('assessment_attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PASSED', 'FAILED', name='assessmentattemptstatus', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_attempts_assessment_id'), 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_user_id'), 'assessment_attempts', ['user_id'], unique=False)
    op.create_table('lesson_datasets',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'dataset_id')
    )
    op.create_table('lesson_prerequisites',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_lesson_id', sa.String(length=36), nullable=False),
    sa.Column('is_hard_blocker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'prerequisite_lesson_id')
    )
    op.create_table('lesson_skills',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'skill_id')
    )
    op.create_table('lesson_tags',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'tag_id')
    )
    op.create_table('related_lessons',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('related_lesson_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'related_lesson_id')
    )
    op.create_table('assessment_answers',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_attempt_id'), 'assessment_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_exercise_id'), 'assessment_answers', ['exercise_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', 'exercise_id')
    )
    op.create_table('exercise_tags',
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id')
    )
    op.add_column('exercise_attempts', sa.Column('submitted_answer', sa.Text(), nullable=True))
    op.add_column(
        'exercise_attempts', sa.Column('hints_used', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'exercise_attempts',
        sa.Column('solution_revealed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # batch_alter_table: SQLite can't ALTER a constraint onto an existing table
    # (only a copy-and-move works there); batch mode picks the right strategy
    # per dialect, so this migration applies cleanly on both SQLite and Postgres.
    with op.batch_alter_table("exercises") as batch_op:
        batch_op.add_column(sa.Column("skill_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("dataset_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"))
        batch_op.create_index(op.f("ix_exercises_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(op.f("ix_exercises_skill_id"), ["skill_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_exercises_dataset_id_datasets", "datasets", ["dataset_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_exercises_skill_id_skills", "skills", ["skill_id"], ["id"], ondelete="SET NULL"
        )
    op.add_column(
        'lesson_progress',
        sa.Column('time_spent_seconds', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('lesson_progress', sa.Column('last_position', sa.String(length=50), nullable=True))
    op.add_column(
        'lesson_progress',
        sa.Column('exercises_completed', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('lessons', sa.Column('completion_criteria', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'completion_criteria')
    op.drop_column('lesson_progress', 'exercises_completed')
    op.drop_column('lesson_progress', 'last_position')
    op.drop_column('lesson_progress', 'time_spent_seconds')
    with op.batch_alter_table("exercises") as batch_op:
        batch_op.drop_constraint("fk_exercises_skill_id_skills", type_="foreignkey")
        batch_op.drop_constraint("fk_exercises_dataset_id_datasets", type_="foreignkey")
        batch_op.drop_index(op.f("ix_exercises_skill_id"))
        batch_op.drop_index(op.f("ix_exercises_dataset_id"))
        batch_op.drop_column("display_order")
        batch_op.drop_column("dataset_id")
        batch_op.drop_column("skill_id")
    op.drop_column('exercise_attempts', 'solution_revealed')
    op.drop_column('exercise_attempts', 'hints_used')
    op.drop_column('exercise_attempts', 'submitted_answer')
    op.drop_table('exercise_tags')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_assessment_answers_exercise_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_attempt_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_table('related_lessons')
    op.drop_table('lesson_tags')
    op.drop_table('lesson_skills')
    op.drop_table('lesson_prerequisites')
    op.drop_table('lesson_datasets')
    op.drop_index(op.f('ix_assessment_attempts_user_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_assessment_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_table('module_prerequisites')
    op.drop_index(op.f('ix_assessments_slug'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_module_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
