"""phase 10 ai layer

Revision ID: b09cef974055
Revises: c754fd66a6ab
Create Date: 2026-09-07 00:46:20.350957

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09cef974055'
down_revision: str | None = 'c754fd66a6ab'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_log',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('feature', sa.Enum('MENTOR', 'SQL_TUTOR', 'SQL_REVIEW', 'SQL_DEBUG', 'SQL_OPTIMIZATION', 'PYTHON_TUTOR', 'PYTHON_REVIEW', 'ANALYSIS_REVIEW', 'INSIGHT_REVIEW', 'DOMAIN_COACH', 'NL_TO_SQL', 'NL_TO_PYTHON', 'EDA_ASSISTANT', 'DATA_EXPLORATION', 'CASE_COACH', 'CASE_INTERVIEWER', 'BEHAVIORAL_INTERVIEWER', 'INTERVIEW_DEBRIEF', 'COMMUNICATION_COACH', 'STORYTELLING_COACH', 'EXEC_SUMMARY', 'LEARNING_PLANNER', 'SKILL_DIAGNOSIS', 'PROJECT_REVIEW', 'KNOWLEDGE_SEARCH', name='aifeature', native_enum=False, length=40), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('context_type', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('request_preview', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_log_feature'), 'ai_audit_log', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_user_id'), 'ai_audit_log', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('feature', sa.Enum('MENTOR', 'SQL_TUTOR', 'SQL_REVIEW', 'SQL_DEBUG', 'SQL_OPTIMIZATION', 'PYTHON_TUTOR', 'PYTHON_REVIEW', 'ANALYSIS_REVIEW', 'INSIGHT_REVIEW', 'DOMAIN_COACH', 'NL_TO_SQL', 'NL_TO_PYTHON', 'EDA_ASSISTANT', 'DATA_EXPLORATION', 'CASE_COACH', 'CASE_INTERVIEWER', 'BEHAVIORAL_INTERVIEWER', 'INTERVIEW_DEBRIEF', 'COMMUNICATION_COACH', 'STORYTELLING_COACH', 'EXEC_SUMMARY', 'LEARNING_PLANNER', 'SKILL_DIAGNOSIS', 'PROJECT_REVIEW', 'KNOWLEDGE_SEARCH', name='aifeature', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context_type', sa.String(length=60), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_context_id'), 'ai_conversations', ['context_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_feature'), 'ai_conversations', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_mistake_memory',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_slug', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('mistake_summary', sa.Text(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('recommended_review', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mistake_memory_skill_slug'), 'ai_mistake_memory', ['skill_slug'], unique=False)
    op.create_index(op.f('ix_ai_mistake_memory_user_id'), 'ai_mistake_memory', ['user_id'], unique=False)
    op.create_table('ai_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('provider_override', sa.String(length=20), nullable=True),
    sa.Column('model_override', sa.String(length=100), nullable=True),
    sa.Column('response_style', sa.String(length=20), nullable=False),
    sa.Column('learning_mode', sa.String(length=20), nullable=False),
    sa.Column('privacy_preference', sa.String(length=20), nullable=False),
    sa.Column('max_context_chars', sa.Integer(), nullable=True),
    sa.Column('daily_request_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_ai_settings_user_id')
    )
    op.create_index(op.f('ix_ai_settings_user_id'), 'ai_settings', ['user_id'], unique=False)
    op.create_table('ai_skill_diagnoses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_slug', sa.String(length=150), nullable=True),
    sa.Column('exercise_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('strength_areas', sa.JSON(), nullable=False),
    sa.Column('improvement_areas', sa.JSON(), nullable=False),
    sa.Column('recommended_exercise_slugs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_skill_diagnoses_exercise_attempt_id'), 'ai_skill_diagnoses', ['exercise_attempt_id'], unique=False)
    op.create_index(op.f('ix_ai_skill_diagnoses_skill_slug'), 'ai_skill_diagnoses', ['skill_slug'], unique=False)
    op.create_index(op.f('ix_ai_skill_diagnoses_user_id'), 'ai_skill_diagnoses', ['user_id'], unique=False)
    op.create_table('ai_usage_counters',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_ai_usage_counter_user_date')
    )
    op.create_index(op.f('ix_ai_usage_counters_usage_date'), 'ai_usage_counters', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_usage_counters_user_id'), 'ai_usage_counters', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='aiconversationrole', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_usage_counters_user_id'), table_name='ai_usage_counters')
    op.drop_index(op.f('ix_ai_usage_counters_usage_date'), table_name='ai_usage_counters')
    op.drop_table('ai_usage_counters')
    op.drop_index(op.f('ix_ai_skill_diagnoses_user_id'), table_name='ai_skill_diagnoses')
    op.drop_index(op.f('ix_ai_skill_diagnoses_skill_slug'), table_name='ai_skill_diagnoses')
    op.drop_index(op.f('ix_ai_skill_diagnoses_exercise_attempt_id'), table_name='ai_skill_diagnoses')
    op.drop_table('ai_skill_diagnoses')
    op.drop_index(op.f('ix_ai_settings_user_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_ai_mistake_memory_user_id'), table_name='ai_mistake_memory')
    op.drop_index(op.f('ix_ai_mistake_memory_skill_slug'), table_name='ai_mistake_memory')
    op.drop_table('ai_mistake_memory')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_feature'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_context_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_ai_audit_log_user_id'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_feature'), table_name='ai_audit_log')
    op.drop_table('ai_audit_log')
    # ### end Alembic commands ###
